/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6 */

#ifndef PB_MODELS_EVENTS_PB_H_INCLUDED
#define PB_MODELS_EVENTS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _IMUEvent { 
    float yaw;
    float pitch;
    float roll;
} IMUEvent;

typedef struct _PitotEvent { 
    float intakePitot;
    float testSectionPitot;
    float diffuserPitot;
} PitotEvent;

typedef struct _ServoPositionEvent { 
    float servo1;
    float servo2;
    float servo3;
    float servo4;
    float servo5;
    float servo6;
} ServoPositionEvent;

typedef struct _StrainEvent { 
    float strain1;
    float strain2;
    float strain3;
    float strain4;
    float strain5;
    float strain6;
} StrainEvent;

typedef struct _SensorEvent { 
    pb_size_t which_event;
    union {
        IMUEvent iMUEvent;
        StrainEvent strainEvent;
        PitotEvent pitotEvent;
    } event;
} SensorEvent;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define IMUEvent_init_default                    {0, 0, 0}
#define PitotEvent_init_default                  {0, 0, 0}
#define StrainEvent_init_default                 {0, 0, 0, 0, 0, 0}
#define ServoPositionEvent_init_default          {0, 0, 0, 0, 0, 0}
#define SensorEvent_init_default                 {0, {IMUEvent_init_default}}
#define IMUEvent_init_zero                       {0, 0, 0}
#define PitotEvent_init_zero                     {0, 0, 0}
#define StrainEvent_init_zero                    {0, 0, 0, 0, 0, 0}
#define ServoPositionEvent_init_zero             {0, 0, 0, 0, 0, 0}
#define SensorEvent_init_zero                    {0, {IMUEvent_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define IMUEvent_yaw_tag                         1
#define IMUEvent_pitch_tag                       2
#define IMUEvent_roll_tag                        3
#define PitotEvent_intakePitot_tag               1
#define PitotEvent_testSectionPitot_tag          2
#define PitotEvent_diffuserPitot_tag             3
#define ServoPositionEvent_servo1_tag            1
#define ServoPositionEvent_servo2_tag            2
#define ServoPositionEvent_servo3_tag            3
#define ServoPositionEvent_servo4_tag            4
#define ServoPositionEvent_servo5_tag            5
#define ServoPositionEvent_servo6_tag            6
#define StrainEvent_strain1_tag                  1
#define StrainEvent_strain2_tag                  2
#define StrainEvent_strain3_tag                  3
#define StrainEvent_strain4_tag                  4
#define StrainEvent_strain5_tag                  5
#define StrainEvent_strain6_tag                  6
#define SensorEvent_iMUEvent_tag                 1
#define SensorEvent_strainEvent_tag              2
#define SensorEvent_pitotEvent_tag               3

/* Struct field encoding specification for nanopb */
#define IMUEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    yaw,               1) \
X(a, STATIC,   SINGULAR, FLOAT,    pitch,             2) \
X(a, STATIC,   SINGULAR, FLOAT,    roll,              3)
#define IMUEvent_CALLBACK NULL
#define IMUEvent_DEFAULT NULL

#define PitotEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    intakePitot,       1) \
X(a, STATIC,   SINGULAR, FLOAT,    testSectionPitot,   2) \
X(a, STATIC,   SINGULAR, FLOAT,    diffuserPitot,     3)
#define PitotEvent_CALLBACK NULL
#define PitotEvent_DEFAULT NULL

#define StrainEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    strain1,           1) \
X(a, STATIC,   SINGULAR, FLOAT,    strain2,           2) \
X(a, STATIC,   SINGULAR, FLOAT,    strain3,           3) \
X(a, STATIC,   SINGULAR, FLOAT,    strain4,           4) \
X(a, STATIC,   SINGULAR, FLOAT,    strain5,           5) \
X(a, STATIC,   SINGULAR, FLOAT,    strain6,           6)
#define StrainEvent_CALLBACK NULL
#define StrainEvent_DEFAULT NULL

#define ServoPositionEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    servo1,            1) \
X(a, STATIC,   SINGULAR, FLOAT,    servo2,            2) \
X(a, STATIC,   SINGULAR, FLOAT,    servo3,            3) \
X(a, STATIC,   SINGULAR, FLOAT,    servo4,            4) \
X(a, STATIC,   SINGULAR, FLOAT,    servo5,            5) \
X(a, STATIC,   SINGULAR, FLOAT,    servo6,            6)
#define ServoPositionEvent_CALLBACK NULL
#define ServoPositionEvent_DEFAULT NULL

#define SensorEvent_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,iMUEvent,event.iMUEvent),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,strainEvent,event.strainEvent),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,pitotEvent,event.pitotEvent),   3)
#define SensorEvent_CALLBACK NULL
#define SensorEvent_DEFAULT NULL
#define SensorEvent_event_iMUEvent_MSGTYPE IMUEvent
#define SensorEvent_event_strainEvent_MSGTYPE StrainEvent
#define SensorEvent_event_pitotEvent_MSGTYPE PitotEvent

extern const pb_msgdesc_t IMUEvent_msg;
extern const pb_msgdesc_t PitotEvent_msg;
extern const pb_msgdesc_t StrainEvent_msg;
extern const pb_msgdesc_t ServoPositionEvent_msg;
extern const pb_msgdesc_t SensorEvent_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define IMUEvent_fields &IMUEvent_msg
#define PitotEvent_fields &PitotEvent_msg
#define StrainEvent_fields &StrainEvent_msg
#define ServoPositionEvent_fields &ServoPositionEvent_msg
#define SensorEvent_fields &SensorEvent_msg

/* Maximum encoded size of messages (where known) */
#define IMUEvent_size                            15
#define PitotEvent_size                          15
#define SensorEvent_size                         32
#define ServoPositionEvent_size                  30
#define StrainEvent_size                         30

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
