/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6 */

#include "events.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(IMUEvent, IMUEvent, AUTO)


PB_BIND(PitotEvent, PitotEvent, AUTO)


PB_BIND(StrainEvent, StrainEvent, AUTO)


PB_BIND(ServoPositionEvent, ServoPositionEvent, AUTO)


PB_BIND(SensorEvent, SensorEvent, AUTO)



